vinculacion-yavirac/frontend-vinculacion

frontend-vinculacion/src/app/pages/encuesta/encuesta.component.css
frontend-vinculacion/src/app/pages/encuesta/encuesta.component.html

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/168

feat:crear pantalla encuesta

---

frontend-vinculacion/src/app/shared/sidebar/sidebar.component.html
package-lock.json

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/189

fix:solucionar responsive en siderbar

---

frontend-vinculacion/src/app/pages/docente-vinculacion/solicitud-vinculacion/solicitud-form/solicitud-form.component.css
frontend-vinculacion/src/app/pages/docente-vinculacion/solicitud-vinculacion/solicitud-form/solicitud-form.component.html
frontend-vinculacion/src/app/shared/shared-routing.module.ts

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/176

feat:crear tabal responsive en solicitud

---

frontend-vinculacion/src/app/pages/docente-vinculacion/proyecto-vinculacion/proyecto-form/proyecto-form.component.html
frontend-vinculacion/src/app/pages/docente-vinculacion/proyecto-vinculacion/proyecto-search/proyecto-search.component.html
frontend-vinculacion/src/app/pages/docente-vinculacion/proyecto-vinculacion/proyecto-search/proyecto-search.component.spec.ts
frontend-vinculacion/src/app/pages/docente-vinculacion/proyecto-vinculacion/proyecto-search/proyecto-search.component.ts
frontend-vinculacion/src/app/pages/docente-vinculacion/solicitud-vinculacion/solicitud-search/solicitud-search.component.html
frontend-vinculacion/src/app/pages/pages.module.ts

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/212

feat:crear search de proyecto

---

frontend-vinculacion/src/app/pages/docente-vinculacion/asignar-fundacion-vinculacion/asignar-fundacion-form/asignar-fundacion-form.component.html
frontend-vinculacion/src/app/pages/docente-vinculacion/asignar-fundacion-vinculacion/asignar-fundacion-search/asignar-fundacion-search.component.html
frontend-vinculacion/src/app/pages/docente-vinculacion/asignar-fundacion-vinculacion/asignar-fundacion-search/asignar-fundacion-search.component.spec.ts
frontend-vinculacion/src/app/pages/docente-vinculacion/asignar-fundacion-vinculacion/asignar-fundacion-search/asignar-fundacion-search.component.ts
frontend-vinculacion/src/app/pages/pages.module.ts

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/213

feat:crear search de asignar fundacion

---

frontend-vinculacion/src/app/pages/pages.module.ts

ActividadesComponent, AnexosComponent, BibliografiaComponent, CertificadosComponent, DatosGeneralesComponent, DocumentosComponent, EmpresaComponent, FirmasComponent, IntegrantesComponent, ObservacionesComponent, PlanDeTrabajoComponent
---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/200

update: pages pestañas

---

frontend-vinculacion/src/app/service/pestanias/actividades/actividades.service.spec.ts
frontend-vinculacion/src/app/service/pestanias/actividades/actividades.service.ts
frontend-vinculacion/src/app/service/pestanias/anexos/anexos.service.spec.ts
frontend-vinculacion/src/app/service/pestanias/anexos/anexos.service.ts
frontend-vinculacion/src/app/service/pestanias/bibliografia/bibliografia.service.spec.ts
frontend-vinculacion/src/app/service/pestanias/bibliografia/bibliografia.service.ts
frontend-vinculacion/src/app/service/pestanias/certificados/certificados.service.spec.ts
frontend-vinculacion/src/app/service/pestanias/certificados/certificados.service.ts
frontend-vinculacion/src/app/service/pestanias/datos-generales/datos-generales.service.spec.ts
frontend-vinculacion/src/app/service/pestanias/datos-generales/datos-generales.service.ts
frontend-vinculacion/src/app/service/pestanias/documentos/documentos.service.spec.ts
frontend-vinculacion/src/app/service/pestanias/documentos/documentos.service.ts
frontend-vinculacion/src/app/service/pestanias/empresa/empresa.service.spec.ts
frontend-vinculacion/src/app/service/pestanias/empresa/empresa.service.ts
frontend-vinculacion/src/app/service/pestanias/firmas/firmas.service.spec.ts
frontend-vinculacion/src/app/service/pestanias/firmas/firmas.service.ts
frontend-vinculacion/src/app/service/pestanias/integrantes/integrantes.service.spec.ts
frontend-vinculacion/src/app/service/pestanias/integrantes/integrantes.service.ts
frontend-vinculacion/src/app/service/pestanias/observaciones/observaciones.service.spec.ts
frontend-vinculacion/src/app/service/pestanias/observaciones/observaciones.service.ts
frontend-vinculacion/src/app/service/pestanias/plan-de-trabajo/plan-de-trabajo.service.spec.ts
frontend-vinculacion/src/app/service/pestanias/plan-de-trabajo/plan-de-trabajo.service.ts

ng generate service service/pestanias/actividades/actividades
ng generate service service/pestanias/anexos/anexos
ng generate service service/pestanias/bibliografia/bibliografia
ng generate service service/pestanias/certificados/certificados
ng generate service service/pestanias/datos-generales/datos-generales
ng generate service service/pestanias/documentos/documentos
ng generate service service/pestanias/empresa/empresa
ng generate service service/pestanias/firmas/firmas
ng generate service service/pestanias/integrantes/integrantes
ng generate service service/pestanias/observaciones/observaciones
ng generate service service/pestanias/plan-de-trabajo/plan-de-trabajo
---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/74#issue-1520052856
- ### EL MR introduce un …

feat: service pestañas

---

frontend-vinculacion/src/app/models/pestanias/actividades.ts
frontend-vinculacion/src/app/models/pestanias/anexos.ts
frontend-vinculacion/src/app/models/pestanias/bibliografia.ts
frontend-vinculacion/src/app/models/pestanias/certificados.ts
frontend-vinculacion/src/app/models/pestanias/datos-generales.ts
frontend-vinculacion/src/app/models/pestanias/documentos.ts
frontend-vinculacion/src/app/models/pestanias/empresa.ts
frontend-vinculacion/src/app/models/pestanias/firmas.ts
frontend-vinculacion/src/app/models/pestanias/integrantes.ts
frontend-vinculacion/src/app/models/pestanias/observaciones.ts
frontend-vinculacion/src/app/models/pestanias/plan-de-trabajo.ts

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/73#issue-1520051657

feat: models pestañas

---

frontend-vinculacion/src/app/pages/informe-control/avance-cumplimiento/avance-cumplimiento.component.html
frontend-vinculacion/src/app/pages/informe-control/observacion-avance/observacion-avance.component.html

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/124

Corecciones

---

frontend-vinculacion/src/app/pages/informe-control/informe-control/informe-control.component.css
frontend-vinculacion/src/app/pages/informe-control/informe-control/informe-control.component.html

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/124

feat:crear pantalla  de informe control

---

frontend-vinculacion/src/app/app-routing.module.ts
frontend-vinculacion/src/app/models/docente-vinculacion/solicitud-vinculacion.ts
frontend-vinculacion/src/app/pages/docente-vinculacion/solicitud-vinculacion/solicitud-form/solicitud-form.component.html
frontend-vinculacion/src/app/pages/docente-vinculacion/solicitud-vinculacion/solicitud-form/solicitud-form.component.ts
frontend-vinculacion/src/app/service/docente-vinculacion/solicitud-vinculacion/solicitud-vinculacion-http.service.ts

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/185

feat:solicitud

---

frontend-vinculacion/src/app/auth/login/login.component.html
frontend-vinculacion/src/app/auth/register/register.component.html
frontend-vinculacion/src/app/models/user/user.ts
frontend-vinculacion/src/app/service/user/user-http.service.spec.ts
frontend-vinculacion/src/app/service/user/user-http.service.ts

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/237

feat: crear servicios de user

---

frontend-vinculacion/src/app/models/docente-tutor/lista-fundacion-tutor.ts
frontend-vinculacion/src/app/pages/docente-tutor/lista-fundacion-tutor/lista-fundacion-tutor-from/lista-fundacion-tutor-from.component.html
frontend-vinculacion/src/app/pages/docente-tutor/lista-fundacion-tutor/lista-fundacion-tutor-from/lista-fundacion-tutor-from.component.ts
frontend-vinculacion/src/app/pages/docente-vinculacion/solicitud-vinculacion/solicitud-form/solicitud-form.component.html
frontend-vinculacion/src/app/service/docente-tutor/lista-fundacion-tutor/lista-fundacion-http.service.ts

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/241

feat: servicio de docente tutor lista fundacion

---

frontend-vinculacion/src/app/pages/docente-tutor/lista-fundacion-tutor/lista-fundacion-tutor-from/lista-fundacion-tutor-from.component.html

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/241

update: implementaciones de nuevas funciones

---

frontend-vinculacion/src/app/pages/estudiante/estudiante-portafolio/estudiante-portafolio-formulario/estudiante-portafolio-formulario.component.css
frontend-vinculacion/src/app/pages/estudiante/estudiante-portafolio/estudiante-portafolio-formulario/estudiante-portafolio-formulario.component.html
frontend-vinculacion/src/app/pages/estudiante/estudiante-portafolio/estudiante-portafolio-portafolio/estudiante-portafolio-portafolio.component.html
frontend-vinculacion/src/app/pages/estudiante/estudiante/estudiante-formulario/estudiante-formulario.component.css
frontend-vinculacion/src/app/pages/estudiante/estudiante/estudiante-formulario/estudiante-formulario.component.html

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/223

Update:pantalla estudiante

---

frontend-vinculacion/src/app/models/informe-control/avance-cumplimiento.ts
frontend-vinculacion/src/app/models/informe-control/informe-control.ts
frontend-vinculacion/src/app/models/informe-control/observacion-avance.ts
frontend-vinculacion/src/app/pages/informe-control/avance-cumplimiento/avance-cumplimiento.component.html
frontend-vinculacion/src/app/pages/informe-control/avance-cumplimiento/avance-cumplimiento.component.ts
frontend-vinculacion/src/app/pages/informe-control/informe-control/informe-control.component.html
frontend-vinculacion/src/app/pages/informe-control/informe-control/informe-control.component.ts
frontend-vinculacion/src/app/pages/informe-control/observacion-avance/observacion-avance.component.html
frontend-vinculacion/src/app/pages/informe-control/observacion-avance/observacion-avance.component.ts
frontend-vinculacion/src/app/service/informe-control/avance-cumplimiento/avance-cumplimiento-http.service.ts
frontend-vinculacion/src/app/service/informe-control/informe-control/informe-control-http.service.ts
frontend-vinculacion/src/app/service/informe-control/observacion-avance/observacion-avance-http.service.ts

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/124

Coreccion de errores

---

frontend-vinculacion/src/app/pages/informe-control/avance-cumplimiento/avance-cumplimiento.component.html
frontend-vinculacion/src/app/pages/informe-control/avance-cumplimiento/avance-cumplimiento.component.ts
frontend-vinculacion/src/app/pages/informe-control/observacion-avance/observacion-avance.component.html
frontend-vinculacion/src/app/pages/informe-control/observacion-avance/observacion-avance.component.ts
frontend-vinculacion/src/app/service/informe-control/avance-cumplimiento/avance-cumplimiento-http.service.ts
frontend-vinculacion/src/app/service/informe-control/observacion-avance/observacion-avance-http.service.ts

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/124

Funcionalidad de texteare

---

frontend-vinculacion/src/app/pages/encuesta/encuesta.component.css
frontend-vinculacion/src/app/pages/encuesta/encuesta.component.html

actualizar pantalla encuesta---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/242

update:actualizar pantalla encuesta

---

frontend-vinculacion/src/app/models/catalogo/TipoPersona.ts
frontend-vinculacion/src/app/pages/coordinador-carrera/agregar-rol/agregar-rol-add/agregar-rol-add.component.ts
frontend-vinculacion/src/app/pages/coordinador-carrera/agregar-rol/agregar-rol-search/agregar-rol-search.component.ts
frontend-vinculacion/src/app/pages/coordinador-carrera/agregar-rol/rol-combobox/rol-combobox.component.ts
frontend-vinculacion/src/app/service/catalogo/catalogo-http.service.spec.ts
frontend-vinculacion/src/app/service/catalogo/catalogo-http.service.ts
frontend-vinculacion/src/app/service/coordinador-carrera/agregar-rol/agregar-rol-http.service.ts
frontend-vinculacion/src/app/service/persona/persona-http.service.ts
frontend-vinculacion/src/app/service/tipo-persona/tipo-persona-http.service.spec.ts
frontend-vinculacion/src/app/service/tipo-persona/tipo-persona-http.service.ts

feat:catalogo

---

frontend-vinculacion/src/app/models/encuesta/encuesta.ts
frontend-vinculacion/src/app/models/encuesta/pregunta.model.ts
frontend-vinculacion/src/app/pages/encuesta/encuesta.component.css
frontend-vinculacion/src/app/pages/encuesta/encuesta.component.html
frontend-vinculacion/src/app/pages/encuesta/encuesta.component.ts
frontend-vinculacion/src/app/service/encuesta/encuesta-http.service.ts

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/288

feat:crear metodo post para pregunta

---

frontend-vinculacion/src/app/pages/encuesta/editar/editar.component.html
frontend-vinculacion/src/app/pages/encuesta/editar/editar.component.ts
frontend-vinculacion/src/app/pages/pages-routing.module.ts
frontend-vinculacion/src/app/pages/pages.module.ts

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/293

feat:metodo update para pregunta

---

frontend-vinculacion/src/app/models/encuesta/respuesta.model.ts
frontend-vinculacion/src/app/pages/encuesta/respuesta/agregar-respuesta/agregar.component.html
frontend-vinculacion/src/app/pages/encuesta/respuesta/agregar-respuesta/agregar.component.ts
frontend-vinculacion/src/app/pages/encuesta/respuesta/respuesta.component.html
frontend-vinculacion/src/app/pages/encuesta/respuesta/respuesta.component.ts
frontend-vinculacion/src/app/pages/pages-routing.module.ts
frontend-vinculacion/src/app/pages/pages.module.ts
frontend-vinculacion/src/app/service/encuesta/respuesta-http.service.ts

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/305

crear:metodo eliminar para respuesta actualizado

---

frontend-vinculacion/src/app/models/pestanias/actividades.ts
frontend-vinculacion/src/app/models/pestanias/anexos.ts
frontend-vinculacion/src/app/models/pestanias/bibliografia.ts
frontend-vinculacion/src/app/models/pestanias/certificados.ts
frontend-vinculacion/src/app/models/pestanias/documentos.ts
frontend-vinculacion/src/app/models/pestanias/empresa.ts
frontend-vinculacion/src/app/models/pestanias/firmas.ts
frontend-vinculacion/src/app/models/pestanias/integrantes.ts
frontend-vinculacion/src/app/models/pestanias/menu.ts
frontend-vinculacion/src/app/models/pestanias/observaciones.ts
frontend-vinculacion/src/app/models/pestanias/plan-de-trabajo.ts

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/311

update: models de pestañas

---

frontend-vinculacion/src/app/pages/encuesta/editar/editar.component.html
frontend-vinculacion/src/app/pages/encuesta/encuesta.component.html
frontend-vinculacion/src/app/pages/encuesta/respuesta/editar-respuesta/editar-respuesta.component.html
frontend-vinculacion/src/app/pages/encuesta/respuesta/editar-respuesta/editar-respuesta.component.ts
frontend-vinculacion/src/app/pages/encuesta/respuesta/respuesta.component.css
frontend-vinculacion/src/app/pages/encuesta/respuesta/respuesta.component.html
frontend-vinculacion/src/app/pages/encuesta/respuesta/respuesta.component.ts
frontend-vinculacion/src/app/pages/pages-routing.module.ts
frontend-vinculacion/src/app/pages/pages.module.ts

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/315

crear:metodo ediar y eliminar

---

frontend-vinculacion/package-lock.json
frontend-vinculacion/package.json
frontend-vinculacion/src/app/pages/encuesta/encuesta.component.html
frontend-vinculacion/src/app/pages/encuesta/encuesta.component.ts
frontend-vinculacion/src/app/pages/encuesta/respuesta/agregar-respuesta/agregar.component.html
frontend-vinculacion/src/app/pages/encuesta/respuesta/editar-respuesta/editar-respuesta.component.html
frontend-vinculacion/src/app/pages/encuesta/respuesta/respuesta.component.html
frontend-vinculacion/src/app/pages/encuesta/respuesta/respuesta.component.ts

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/322

update: editar y eliminar funcionales

---

frontend-vinculacion/src/app/pages/encuesta/agregar-pregunta/agregar-pregunta.component.html
frontend-vinculacion/src/app/pages/encuesta/agregar-pregunta/agregar-pregunta.component.ts
frontend-vinculacion/src/app/pages/encuesta/editar/editar.component.html
frontend-vinculacion/src/app/pages/encuesta/editar/editar.component.ts
frontend-vinculacion/src/app/pages/encuesta/encuesta.component.html
frontend-vinculacion/src/app/pages/encuesta/encuesta.component.ts
frontend-vinculacion/src/app/pages/encuesta/respuesta/editar-respuesta/editar-respuesta.component.html
frontend-vinculacion/src/app/pages/encuesta/respuesta/respuesta.component.ts
frontend-vinculacion/src/app/pages/pages-routing.module.ts
frontend-vinculacion/src/app/pages/pages.module.ts

---
- https://github.com/vinculacion-yavirac/frontend-vinculacion/issues/328

feat: pruebas respuesta realizadas

---

frontend-vinculacion/src/app/models/vista/vistaListaRoles.ts
frontend-vinculacion/src/app/pages/coordinador-carrera/agregar-rol/agregar-rol-add/agregar-rol-add.component.html
frontend-vinculacion/src/app/pages/coordinador-carrera/lista-estudiantes/lista-estudiantes-form/lista-estudiantes-form.component.html
frontend-vinculacion/src/app/pages/coordinador-carrera/lista-estudiantes/lista-estudiantes-form/lista-estudiantes-form.component.ts
frontend-vinculacion/src/app/pages/coordinador-carrera/redireccionar/redireccionar-principal/redireccionar-principal.component.css
frontend-vinculacion/src/app/pages/coordinador-carrera/redireccionar/redireccionar-principal/redireccionar-principal.component.html
frontend-vinculacion/src/app/pages/docente-tutor/lista-fundacion-tutor/lista-fundacion-tutor-from/lista-fundacion-tutor-from.component.html
frontend-vinculacion/src/app/service/vista/vistaFundacionEstudiante/vista-fundacion-estudiante-http.service.ts
frontend-vinculacion/src/app/service/vista/vistaListaRoles/vista-lista-roles-http.service.spec.ts
frontend-vinculacion/src/app/service/vista/vistaListaRoles/vista-lista-roles-http.service.ts

feature:arreglo a pantallas
